# Generated by Django 4.2.5 on 2023-09-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('description', models.TextField(default=None)),
                ('category', models.CharField(default=None, max_length=50)),
                ('product_image', models.ImageField(default=None, upload_to='uploads/images')),
            ],
        ),
    ]
